/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package megacasting;

import javax.swing.plaf.basic.BasicTabbedPaneUI;

/**
 *
 * @author Mousse
 */
public class jFrameOffreDetails extends javax.swing.JFrame {

    /**
     * Creates new form jFrameOffreDetails
     */
    public jFrameOffreDetails() {
        
        
        initComponents();
        
        tabbedPaneOffreDetails.setUI(new BasicTabbedPaneUI() {

            @Override
            protected int calculateTabAreaHeight(int tabPlacement, int horizRunCount, int maxTabHeight) {
                return 0; //To change body of generated methods, choose Tools | Templates.
            }
        });
                
        // Gérer l'onglet à ouvrir selon le bouton sélectionné (Ajouter / Modifier) dans jPanelOffre
        tabbedPaneOffreDetails.setSelectedIndex(0);
        
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPaneOffreDetails = new javax.swing.JTabbedPane();
        panelUpdateOffre = new javax.swing.JPanel();
        labelUpdateOffre_reference = new javax.swing.JLabel();
        textFieldUpdateOffre_reference = new javax.swing.JTextField();
        labelUpdateOffre_libelle = new javax.swing.JLabel();
        textFieldUpdateOffre_libelle = new javax.swing.JTextField();
        labelUpdateOffre_datePublication = new javax.swing.JLabel();
        labelUpdateOffre_dateDebutContrat = new javax.swing.JLabel();
        labelUpdateOffre_dateFinContrat = new javax.swing.JLabel();
        labelUpdateOffre_descriptionPoste = new javax.swing.JLabel();
        scrollPaneUpdateOffre_descriptionPoste = new javax.swing.JScrollPane();
        textAreaUpdateOffre_descriptionPoste = new javax.swing.JTextArea();
        labelUpdateOffre_descriptionProfil = new javax.swing.JLabel();
        scrollPaneUpdateOffre_descriptionProfil = new javax.swing.JScrollPane();
        textAreaUpdateOffre_descriptionProfil = new javax.swing.JTextArea();
        labelUpdateOffre_annonceur = new javax.swing.JLabel();
        comboBoxUpdateOffre_annonceur = new javax.swing.JComboBox();
        labelUpdateOffre_contrat = new javax.swing.JLabel();
        comboBoxUpdateOffre_contrat = new javax.swing.JComboBox();
        labelUpdateOffre_domaine = new javax.swing.JLabel();
        comboBoxUpdateOffre_domaine = new javax.swing.JComboBox();
        labelUpdateOffre_metier = new javax.swing.JLabel();
        comboBoxUpdateOffre_metier = new javax.swing.JComboBox();
        buttonUpdateOffre_valid = new javax.swing.JButton();
        buttonUpdateOffre_annul = new javax.swing.JButton();
        panelInsertOffre = new javax.swing.JPanel();
        labelInsertOffre_reference = new javax.swing.JLabel();
        textFieldInsertOffre_reference = new javax.swing.JTextField();
        labelInsertOffre_libelle = new javax.swing.JLabel();
        textFieldInsertOffre_libelle = new javax.swing.JTextField();
        labelInsertOffre_datePublication = new javax.swing.JLabel();
        labelInsertOffre_dateDebutContrat = new javax.swing.JLabel();
        labelInsertOffre_dateFinContrat = new javax.swing.JLabel();
        labelInsertOffre_descriptionPoste = new javax.swing.JLabel();
        scrollPaneInsertOffre_descriptionPoste = new javax.swing.JScrollPane();
        textAreaInsertOffre_descriptionPoste = new javax.swing.JTextArea();
        labelInsertOffre_descriptionProfil = new javax.swing.JLabel();
        scrollPaneInsertOffre_descriptionProfil = new javax.swing.JScrollPane();
        textAreaInsertOffre_descriptionProfil = new javax.swing.JTextArea();
        labelInsertOffre_annonceur = new javax.swing.JLabel();
        comboBoxInsertOffre_annonceur = new javax.swing.JComboBox();
        labelInsertOffre_contrat = new javax.swing.JLabel();
        comboBoxInsertOffre_contrat = new javax.swing.JComboBox();
        labelInsertOffre_domaine = new javax.swing.JLabel();
        comboBoxInsertOffre_domaine = new javax.swing.JComboBox();
        labelInsertOffre_metier = new javax.swing.JLabel();
        comboBoxInsertOffre_metier = new javax.swing.JComboBox();
        buttonInsertOffre_valid = new javax.swing.JButton();
        buttonInsertOffre_annul = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelUpdateOffre_reference.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelUpdateOffre_reference.setText("Référence");

        labelUpdateOffre_libelle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelUpdateOffre_libelle.setText("Libellé");

        labelUpdateOffre_datePublication.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelUpdateOffre_datePublication.setText("Date de publication");

        labelUpdateOffre_dateDebutContrat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelUpdateOffre_dateDebutContrat.setText("Début du contrat");

        labelUpdateOffre_dateFinContrat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelUpdateOffre_dateFinContrat.setText("Fin du contrat");

        labelUpdateOffre_descriptionPoste.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelUpdateOffre_descriptionPoste.setText("Description poste");

        textAreaUpdateOffre_descriptionPoste.setColumns(20);
        textAreaUpdateOffre_descriptionPoste.setRows(5);
        scrollPaneUpdateOffre_descriptionPoste.setViewportView(textAreaUpdateOffre_descriptionPoste);

        labelUpdateOffre_descriptionProfil.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelUpdateOffre_descriptionProfil.setText("Description profil");

        textAreaUpdateOffre_descriptionProfil.setColumns(20);
        textAreaUpdateOffre_descriptionProfil.setRows(5);
        scrollPaneUpdateOffre_descriptionProfil.setViewportView(textAreaUpdateOffre_descriptionProfil);

        labelUpdateOffre_annonceur.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelUpdateOffre_annonceur.setText("Annonceur");

        comboBoxUpdateOffre_annonceur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labelUpdateOffre_contrat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelUpdateOffre_contrat.setText("Contrat");

        comboBoxUpdateOffre_contrat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labelUpdateOffre_domaine.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelUpdateOffre_domaine.setText("Domaine");

        comboBoxUpdateOffre_domaine.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labelUpdateOffre_metier.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelUpdateOffre_metier.setText("Métier");

        comboBoxUpdateOffre_metier.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonUpdateOffre_valid.setText("Confirmer");

        buttonUpdateOffre_annul.setText("Annuler");

        javax.swing.GroupLayout panelUpdateOffreLayout = new javax.swing.GroupLayout(panelUpdateOffre);
        panelUpdateOffre.setLayout(panelUpdateOffreLayout);
        panelUpdateOffreLayout.setHorizontalGroup(
            panelUpdateOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateOffreLayout.createSequentialGroup()
                .addGroup(panelUpdateOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUpdateOffreLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelUpdateOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelUpdateOffreLayout.createSequentialGroup()
                                .addComponent(labelUpdateOffre_metier, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comboBoxUpdateOffre_metier, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelUpdateOffreLayout.createSequentialGroup()
                                .addComponent(labelUpdateOffre_contrat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comboBoxUpdateOffre_contrat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelUpdateOffreLayout.createSequentialGroup()
                                .addComponent(labelUpdateOffre_reference, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldUpdateOffre_reference))
                            .addGroup(panelUpdateOffreLayout.createSequentialGroup()
                                .addComponent(labelUpdateOffre_libelle, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldUpdateOffre_libelle))
                            .addComponent(labelUpdateOffre_datePublication, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelUpdateOffre_dateDebutContrat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelUpdateOffre_dateFinContrat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelUpdateOffreLayout.createSequentialGroup()
                                .addComponent(labelUpdateOffre_descriptionPoste, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(scrollPaneUpdateOffre_descriptionPoste, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                            .addGroup(panelUpdateOffreLayout.createSequentialGroup()
                                .addComponent(labelUpdateOffre_descriptionProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(scrollPaneUpdateOffre_descriptionProfil))
                            .addGroup(panelUpdateOffreLayout.createSequentialGroup()
                                .addComponent(labelUpdateOffre_annonceur, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comboBoxUpdateOffre_annonceur, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelUpdateOffreLayout.createSequentialGroup()
                                .addComponent(labelUpdateOffre_domaine, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comboBoxUpdateOffre_domaine, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(panelUpdateOffreLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(buttonUpdateOffre_valid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonUpdateOffre_annul)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelUpdateOffreLayout.setVerticalGroup(
            panelUpdateOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateOffreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUpdateOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUpdateOffre_reference)
                    .addComponent(textFieldUpdateOffre_reference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUpdateOffre_libelle)
                    .addComponent(textFieldUpdateOffre_libelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelUpdateOffre_datePublication)
                .addGap(18, 18, 18)
                .addComponent(labelUpdateOffre_dateDebutContrat)
                .addGap(18, 18, 18)
                .addComponent(labelUpdateOffre_dateFinContrat)
                .addGap(18, 18, 18)
                .addGroup(panelUpdateOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelUpdateOffre_descriptionPoste)
                    .addComponent(scrollPaneUpdateOffre_descriptionPoste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelUpdateOffre_descriptionProfil)
                    .addComponent(scrollPaneUpdateOffre_descriptionProfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUpdateOffre_annonceur)
                    .addComponent(comboBoxUpdateOffre_annonceur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUpdateOffre_contrat)
                    .addComponent(comboBoxUpdateOffre_contrat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUpdateOffre_domaine)
                    .addComponent(comboBoxUpdateOffre_domaine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUpdateOffre_metier)
                    .addComponent(comboBoxUpdateOffre_metier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonUpdateOffre_valid)
                    .addComponent(buttonUpdateOffre_annul))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        tabbedPaneOffreDetails.addTab("tab2", panelUpdateOffre);

        labelInsertOffre_reference.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelInsertOffre_reference.setText("Référence");

        labelInsertOffre_libelle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelInsertOffre_libelle.setText("Libellé");

        labelInsertOffre_datePublication.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelInsertOffre_datePublication.setText("Date de publication");

        labelInsertOffre_dateDebutContrat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelInsertOffre_dateDebutContrat.setText("Début du contrat");

        labelInsertOffre_dateFinContrat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelInsertOffre_dateFinContrat.setText("Fin du contrat");

        labelInsertOffre_descriptionPoste.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelInsertOffre_descriptionPoste.setText("Description poste");

        textAreaInsertOffre_descriptionPoste.setColumns(20);
        textAreaInsertOffre_descriptionPoste.setRows(5);
        scrollPaneInsertOffre_descriptionPoste.setViewportView(textAreaInsertOffre_descriptionPoste);

        labelInsertOffre_descriptionProfil.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelInsertOffre_descriptionProfil.setText("Description profil");

        textAreaInsertOffre_descriptionProfil.setColumns(20);
        textAreaInsertOffre_descriptionProfil.setRows(5);
        scrollPaneInsertOffre_descriptionProfil.setViewportView(textAreaInsertOffre_descriptionProfil);

        labelInsertOffre_annonceur.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelInsertOffre_annonceur.setText("Annonceur");

        comboBoxInsertOffre_annonceur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labelInsertOffre_contrat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelInsertOffre_contrat.setText("Contrat");

        comboBoxInsertOffre_contrat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labelInsertOffre_domaine.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelInsertOffre_domaine.setText("Domaine");

        comboBoxInsertOffre_domaine.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labelInsertOffre_metier.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelInsertOffre_metier.setText("Métier");

        comboBoxInsertOffre_metier.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonInsertOffre_valid.setText("Confirmer");

        buttonInsertOffre_annul.setText("Annuler");

        javax.swing.GroupLayout panelInsertOffreLayout = new javax.swing.GroupLayout(panelInsertOffre);
        panelInsertOffre.setLayout(panelInsertOffreLayout);
        panelInsertOffreLayout.setHorizontalGroup(
            panelInsertOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInsertOffreLayout.createSequentialGroup()
                .addGroup(panelInsertOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInsertOffreLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelInsertOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelInsertOffreLayout.createSequentialGroup()
                                .addComponent(labelInsertOffre_metier, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comboBoxInsertOffre_metier, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelInsertOffreLayout.createSequentialGroup()
                                .addComponent(labelInsertOffre_contrat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comboBoxInsertOffre_contrat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelInsertOffreLayout.createSequentialGroup()
                                .addComponent(labelInsertOffre_reference, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldInsertOffre_reference))
                            .addGroup(panelInsertOffreLayout.createSequentialGroup()
                                .addComponent(labelInsertOffre_libelle, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldInsertOffre_libelle))
                            .addComponent(labelInsertOffre_datePublication, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelInsertOffre_dateDebutContrat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelInsertOffre_dateFinContrat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelInsertOffreLayout.createSequentialGroup()
                                .addComponent(labelInsertOffre_descriptionPoste, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(scrollPaneInsertOffre_descriptionPoste, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                            .addGroup(panelInsertOffreLayout.createSequentialGroup()
                                .addComponent(labelInsertOffre_descriptionProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(scrollPaneInsertOffre_descriptionProfil))
                            .addGroup(panelInsertOffreLayout.createSequentialGroup()
                                .addComponent(labelInsertOffre_annonceur, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comboBoxInsertOffre_annonceur, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelInsertOffreLayout.createSequentialGroup()
                                .addComponent(labelInsertOffre_domaine, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comboBoxInsertOffre_domaine, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(panelInsertOffreLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(buttonInsertOffre_valid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonInsertOffre_annul)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInsertOffreLayout.setVerticalGroup(
            panelInsertOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInsertOffreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInsertOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelInsertOffre_reference)
                    .addComponent(textFieldInsertOffre_reference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInsertOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelInsertOffre_libelle)
                    .addComponent(textFieldInsertOffre_libelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelInsertOffre_datePublication)
                .addGap(18, 18, 18)
                .addComponent(labelInsertOffre_dateDebutContrat)
                .addGap(18, 18, 18)
                .addComponent(labelInsertOffre_dateFinContrat)
                .addGap(18, 18, 18)
                .addGroup(panelInsertOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelInsertOffre_descriptionPoste)
                    .addComponent(scrollPaneInsertOffre_descriptionPoste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInsertOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelInsertOffre_descriptionProfil)
                    .addComponent(scrollPaneInsertOffre_descriptionProfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInsertOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelInsertOffre_annonceur)
                    .addComponent(comboBoxInsertOffre_annonceur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInsertOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelInsertOffre_contrat)
                    .addComponent(comboBoxInsertOffre_contrat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInsertOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelInsertOffre_domaine)
                    .addComponent(comboBoxInsertOffre_domaine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInsertOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelInsertOffre_metier)
                    .addComponent(comboBoxInsertOffre_metier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInsertOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonInsertOffre_valid)
                    .addComponent(buttonInsertOffre_annul))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        tabbedPaneOffreDetails.addTab("tab2", panelInsertOffre);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPaneOffreDetails)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPaneOffreDetails)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrameOffreDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrameOffreDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrameOffreDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrameOffreDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrameOffreDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonInsertOffre_annul;
    private javax.swing.JButton buttonInsertOffre_valid;
    private javax.swing.JButton buttonUpdateOffre_annul;
    private javax.swing.JButton buttonUpdateOffre_valid;
    private javax.swing.JComboBox comboBoxInsertOffre_annonceur;
    private javax.swing.JComboBox comboBoxInsertOffre_contrat;
    private javax.swing.JComboBox comboBoxInsertOffre_domaine;
    private javax.swing.JComboBox comboBoxInsertOffre_metier;
    private javax.swing.JComboBox comboBoxUpdateOffre_annonceur;
    private javax.swing.JComboBox comboBoxUpdateOffre_contrat;
    private javax.swing.JComboBox comboBoxUpdateOffre_domaine;
    private javax.swing.JComboBox comboBoxUpdateOffre_metier;
    private javax.swing.JLabel labelInsertOffre_annonceur;
    private javax.swing.JLabel labelInsertOffre_contrat;
    private javax.swing.JLabel labelInsertOffre_dateDebutContrat;
    private javax.swing.JLabel labelInsertOffre_dateFinContrat;
    private javax.swing.JLabel labelInsertOffre_datePublication;
    private javax.swing.JLabel labelInsertOffre_descriptionPoste;
    private javax.swing.JLabel labelInsertOffre_descriptionProfil;
    private javax.swing.JLabel labelInsertOffre_domaine;
    private javax.swing.JLabel labelInsertOffre_libelle;
    private javax.swing.JLabel labelInsertOffre_metier;
    private javax.swing.JLabel labelInsertOffre_reference;
    private javax.swing.JLabel labelUpdateOffre_annonceur;
    private javax.swing.JLabel labelUpdateOffre_contrat;
    private javax.swing.JLabel labelUpdateOffre_dateDebutContrat;
    private javax.swing.JLabel labelUpdateOffre_dateFinContrat;
    private javax.swing.JLabel labelUpdateOffre_datePublication;
    private javax.swing.JLabel labelUpdateOffre_descriptionPoste;
    private javax.swing.JLabel labelUpdateOffre_descriptionProfil;
    private javax.swing.JLabel labelUpdateOffre_domaine;
    private javax.swing.JLabel labelUpdateOffre_libelle;
    private javax.swing.JLabel labelUpdateOffre_metier;
    private javax.swing.JLabel labelUpdateOffre_reference;
    private javax.swing.JPanel panelInsertOffre;
    private javax.swing.JPanel panelUpdateOffre;
    private javax.swing.JScrollPane scrollPaneInsertOffre_descriptionPoste;
    private javax.swing.JScrollPane scrollPaneInsertOffre_descriptionProfil;
    private javax.swing.JScrollPane scrollPaneUpdateOffre_descriptionPoste;
    private javax.swing.JScrollPane scrollPaneUpdateOffre_descriptionProfil;
    private javax.swing.JTabbedPane tabbedPaneOffreDetails;
    private javax.swing.JTextArea textAreaInsertOffre_descriptionPoste;
    private javax.swing.JTextArea textAreaInsertOffre_descriptionProfil;
    private javax.swing.JTextArea textAreaUpdateOffre_descriptionPoste;
    private javax.swing.JTextArea textAreaUpdateOffre_descriptionProfil;
    private javax.swing.JTextField textFieldInsertOffre_libelle;
    private javax.swing.JTextField textFieldInsertOffre_reference;
    private javax.swing.JTextField textFieldUpdateOffre_libelle;
    private javax.swing.JTextField textFieldUpdateOffre_reference;
    // End of variables declaration//GEN-END:variables
}
