/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package megacasting;

import javax.swing.plaf.basic.BasicTabbedPaneUI;

/**
 *
 * @author Mousse
 */
public class jFrameMegaCasting extends javax.swing.JFrame {

    /**
     * Creates new form jFrameMegaCasting
     */
    public jFrameMegaCasting() {
        initComponents();
        tabbedPanePers.setUI(new BasicTabbedPaneUI() {

            @Override
            protected int calculateTabAreaHeight(int tabPlacement, int horizRunCount, int maxTabHeight) {
                return 0; //To change body of generated methods, choose Tools | Templates.
            }
            
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        panelOffre = new javax.swing.JPanel();
        panelOffre_list = new javax.swing.JPanel();
        scrollPanelOffre_list = new javax.swing.JScrollPane();
        tableOffre_list = new javax.swing.JTable();
        panelOffre_form = new javax.swing.JPanel();
        labelOffre_1 = new javax.swing.JLabel();
        textFieldOffre_4 = new javax.swing.JTextField();
        labelOffre_3 = new javax.swing.JLabel();
        textFieldOffre_1 = new javax.swing.JTextField();
        labelOffre_4 = new javax.swing.JLabel();
        textFieldOffre_2 = new javax.swing.JTextField();
        labelOffre_2 = new javax.swing.JLabel();
        textFieldOffre_3 = new javax.swing.JTextField();
        panelOffre_valid = new javax.swing.JPanel();
        buttonOffre_insert = new javax.swing.JButton();
        buttonOffre_delete = new javax.swing.JButton();
        buttonOffre_update = new javax.swing.JButton();
        panelSociete = new javax.swing.JPanel();
        panelSociete_sort = new javax.swing.JPanel();
        comboBoxSociete_sort = new javax.swing.JComboBox();
        panelSociete_list = new javax.swing.JPanel();
        scrollPanelSociete_list = new javax.swing.JScrollPane();
        tableSociete_list = new javax.swing.JTable();
        panelSociete_form = new javax.swing.JPanel();
        labelSociete_Nom = new javax.swing.JLabel();
        textFieldSociete_Nom = new javax.swing.JTextField();
        labelSociete_Responsable = new javax.swing.JLabel();
        textFieldSociete_Responsable = new javax.swing.JTextField();
        labelSociete_Siret = new javax.swing.JLabel();
        textFieldSociete_Siret = new javax.swing.JTextField();
        panelSociete_valid = new javax.swing.JPanel();
        buttonSociete_insert = new javax.swing.JButton();
        buttonSociete_delete = new javax.swing.JButton();
        buttonSociete_update = new javax.swing.JButton();
        panelPers = new javax.swing.JPanel();
        panelPers_sort = new javax.swing.JPanel();
        comboBoxPers_sort = new javax.swing.JComboBox();
        tabbedPanePers = new javax.swing.JTabbedPane();
        panelEmpl = new javax.swing.JPanel();
        panelEmpl_list = new javax.swing.JPanel();
        scrollPanelEmpl_list = new javax.swing.JScrollPane();
        tableEmpl_list = new javax.swing.JTable();
        panelEmpl_form = new javax.swing.JPanel();
        labelEmpl_nom = new javax.swing.JLabel();
        textFieldEmpl_nom = new javax.swing.JTextField();
        labelEmpl_prenom = new javax.swing.JLabel();
        textFieldEmpl_prenom = new javax.swing.JTextField();
        labelEmpl_poste = new javax.swing.JLabel();
        textFieldEmpl_poste = new javax.swing.JTextField();
        labelEmpl_habilitation = new javax.swing.JLabel();
        textFieldEmpl_habilitation = new javax.swing.JTextField();
        panelEmpl_valid = new javax.swing.JPanel();
        buttonEmpl_insert = new javax.swing.JButton();
        buttonEmpl_delete = new javax.swing.JButton();
        buttonEmpl_update = new javax.swing.JButton();
        panelCand = new javax.swing.JPanel();
        panelCand_list = new javax.swing.JPanel();
        scrollPanelCand_list = new javax.swing.JScrollPane();
        tableCand_list = new javax.swing.JTable();
        panelCand_form = new javax.swing.JPanel();
        labelCand_nom = new javax.swing.JLabel();
        textFieldCand_nom = new javax.swing.JTextField();
        labelCand_prenom = new javax.swing.JLabel();
        textFieldCand_prenom = new javax.swing.JTextField();
        labelCand_dateNaissance = new javax.swing.JLabel();
        labelCand_pays = new javax.swing.JLabel();
        textFieldCand_pays = new javax.swing.JTextField();
        panelCand_valid = new javax.swing.JPanel();
        buttonCand_insert = new javax.swing.JButton();
        buttonCand_delete = new javax.swing.JButton();
        buttonCand_update = new javax.swing.JButton();
        panelParam = new javax.swing.JPanel();
        panelContrat = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        panelMetier = new javax.swing.JPanel();
        panelDomaine = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane.setName(""); // NOI18N

        panelOffre_list.setBorder(javax.swing.BorderFactory.createTitledBorder("Liste des offres"));

        tableOffre_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPanelOffre_list.setViewportView(tableOffre_list);

        javax.swing.GroupLayout panelOffre_listLayout = new javax.swing.GroupLayout(panelOffre_list);
        panelOffre_list.setLayout(panelOffre_listLayout);
        panelOffre_listLayout.setHorizontalGroup(
            panelOffre_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOffre_listLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelOffre_list, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelOffre_listLayout.setVerticalGroup(
            panelOffre_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOffre_listLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelOffre_list)
                .addContainerGap())
        );

        panelOffre_form.setBorder(javax.swing.BorderFactory.createTitledBorder("Formulaire"));

        labelOffre_1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelOffre_1.setText("jLabel1");

        labelOffre_3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelOffre_3.setText("jLabel1");

        labelOffre_4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelOffre_4.setText("jLabel1");

        labelOffre_2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelOffre_2.setText("jLabel1");

        javax.swing.GroupLayout panelOffre_formLayout = new javax.swing.GroupLayout(panelOffre_form);
        panelOffre_form.setLayout(panelOffre_formLayout);
        panelOffre_formLayout.setHorizontalGroup(
            panelOffre_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOffre_formLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOffre_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelOffre_1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelOffre_2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelOffre_3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelOffre_4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelOffre_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldOffre_3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldOffre_1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldOffre_2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldOffre_4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelOffre_formLayout.setVerticalGroup(
            panelOffre_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOffre_formLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(panelOffre_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldOffre_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelOffre_1))
                .addGap(27, 27, 27)
                .addGroup(panelOffre_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOffre_2)
                    .addComponent(textFieldOffre_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panelOffre_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldOffre_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelOffre_3))
                .addGap(31, 31, 31)
                .addGroup(panelOffre_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldOffre_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelOffre_4))
                .addContainerGap(336, Short.MAX_VALUE))
        );

        panelOffre_valid.setBorder(javax.swing.BorderFactory.createTitledBorder("Valider"));

        buttonOffre_insert.setLabel("Ajouter");

        buttonOffre_delete.setLabel("Supprimer");

        buttonOffre_update.setLabel("Modifier");

        javax.swing.GroupLayout panelOffre_validLayout = new javax.swing.GroupLayout(panelOffre_valid);
        panelOffre_valid.setLayout(panelOffre_validLayout);
        panelOffre_validLayout.setHorizontalGroup(
            panelOffre_validLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOffre_validLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonOffre_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonOffre_update, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonOffre_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelOffre_validLayout.setVerticalGroup(
            panelOffre_validLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOffre_validLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOffre_validLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonOffre_insert, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(buttonOffre_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonOffre_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelOffreLayout = new javax.swing.GroupLayout(panelOffre);
        panelOffre.setLayout(panelOffreLayout);
        panelOffreLayout.setHorizontalGroup(
            panelOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOffreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelOffre_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelOffre_form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelOffre_valid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelOffreLayout.setVerticalGroup(
            panelOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOffreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelOffre_list, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelOffreLayout.createSequentialGroup()
                        .addComponent(panelOffre_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelOffre_valid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane.addTab("Offres", panelOffre);

        panelSociete_sort.setBorder(javax.swing.BorderFactory.createTitledBorder("Tri"));

        comboBoxSociete_sort.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelSociete_sortLayout = new javax.swing.GroupLayout(panelSociete_sort);
        panelSociete_sort.setLayout(panelSociete_sortLayout);
        panelSociete_sortLayout.setHorizontalGroup(
            panelSociete_sortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSociete_sortLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(comboBoxSociete_sort, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSociete_sortLayout.setVerticalGroup(
            panelSociete_sortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSociete_sortLayout.createSequentialGroup()
                .addComponent(comboBoxSociete_sort, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelSociete_list.setBorder(javax.swing.BorderFactory.createTitledBorder("Liste des sociétés"));

        tableSociete_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Raison Sociale", "Responsable"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPanelSociete_list.setViewportView(tableSociete_list);

        javax.swing.GroupLayout panelSociete_listLayout = new javax.swing.GroupLayout(panelSociete_list);
        panelSociete_list.setLayout(panelSociete_listLayout);
        panelSociete_listLayout.setHorizontalGroup(
            panelSociete_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSociete_listLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelSociete_list, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelSociete_listLayout.setVerticalGroup(
            panelSociete_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSociete_listLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelSociete_list)
                .addContainerGap())
        );

        panelSociete_form.setBorder(javax.swing.BorderFactory.createTitledBorder("Formulaire"));

        labelSociete_Nom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelSociete_Nom.setText("Raison sociale");

        labelSociete_Responsable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelSociete_Responsable.setText("Responsable");

        labelSociete_Siret.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelSociete_Siret.setText("Siret");

        javax.swing.GroupLayout panelSociete_formLayout = new javax.swing.GroupLayout(panelSociete_form);
        panelSociete_form.setLayout(panelSociete_formLayout);
        panelSociete_formLayout.setHorizontalGroup(
            panelSociete_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSociete_formLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSociete_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSociete_formLayout.createSequentialGroup()
                        .addGroup(panelSociete_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSociete_Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSociete_Responsable, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelSociete_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldSociete_Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldSociete_Responsable, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelSociete_formLayout.createSequentialGroup()
                        .addComponent(labelSociete_Siret, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textFieldSociete_Siret, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSociete_formLayout.setVerticalGroup(
            panelSociete_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSociete_formLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(panelSociete_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldSociete_Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSociete_Nom))
                .addGap(27, 27, 27)
                .addGroup(panelSociete_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldSociete_Responsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSociete_Responsable))
                .addGap(26, 26, 26)
                .addGroup(panelSociete_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldSociete_Siret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSociete_Siret))
                .addContainerGap(312, Short.MAX_VALUE))
        );

        textFieldSociete_Nom.getAccessibleContext().setAccessibleName("Raison sociale");
        textFieldSociete_Responsable.getAccessibleContext().setAccessibleName("Responsable");
        textFieldSociete_Siret.getAccessibleContext().setAccessibleName("Siret");

        panelSociete_valid.setBorder(javax.swing.BorderFactory.createTitledBorder("Valider"));

        buttonSociete_insert.setLabel("Ajouter");

        buttonSociete_delete.setLabel("Supprimer");

        buttonSociete_update.setLabel("Modifier");

        javax.swing.GroupLayout panelSociete_validLayout = new javax.swing.GroupLayout(panelSociete_valid);
        panelSociete_valid.setLayout(panelSociete_validLayout);
        panelSociete_validLayout.setHorizontalGroup(
            panelSociete_validLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSociete_validLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonSociete_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonSociete_update, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonSociete_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelSociete_validLayout.setVerticalGroup(
            panelSociete_validLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSociete_validLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSociete_validLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonSociete_insert, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(buttonSociete_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonSociete_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelSocieteLayout = new javax.swing.GroupLayout(panelSociete);
        panelSociete.setLayout(panelSocieteLayout);
        panelSocieteLayout.setHorizontalGroup(
            panelSocieteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSocieteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSocieteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelSociete_sort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelSocieteLayout.createSequentialGroup()
                        .addComponent(panelSociete_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelSocieteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelSociete_form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelSociete_valid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelSocieteLayout.setVerticalGroup(
            panelSocieteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSocieteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSociete_sort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSocieteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelSociete_list, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelSocieteLayout.createSequentialGroup()
                        .addComponent(panelSociete_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelSociete_valid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane.addTab("Société", panelSociete);

        panelPers_sort.setBorder(javax.swing.BorderFactory.createTitledBorder("Tri"));

        comboBoxPers_sort.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2" }));
        comboBoxPers_sort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxPers_sortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPers_sortLayout = new javax.swing.GroupLayout(panelPers_sort);
        panelPers_sort.setLayout(panelPers_sortLayout);
        panelPers_sortLayout.setHorizontalGroup(
            panelPers_sortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPers_sortLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(comboBoxPers_sort, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPers_sortLayout.setVerticalGroup(
            panelPers_sortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPers_sortLayout.createSequentialGroup()
                .addComponent(comboBoxPers_sort, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelEmpl_list.setBorder(javax.swing.BorderFactory.createTitledBorder("Liste des employés"));

        tableEmpl_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nom", "Prénom", "Poste", "Habilitation"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPanelEmpl_list.setViewportView(tableEmpl_list);

        javax.swing.GroupLayout panelEmpl_listLayout = new javax.swing.GroupLayout(panelEmpl_list);
        panelEmpl_list.setLayout(panelEmpl_listLayout);
        panelEmpl_listLayout.setHorizontalGroup(
            panelEmpl_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpl_listLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelEmpl_list, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelEmpl_listLayout.setVerticalGroup(
            panelEmpl_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpl_listLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelEmpl_list)
                .addContainerGap())
        );

        panelEmpl_form.setBorder(javax.swing.BorderFactory.createTitledBorder("Formulaire"));

        labelEmpl_nom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelEmpl_nom.setText("Nom");

        labelEmpl_prenom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelEmpl_prenom.setText("Prénom");

        labelEmpl_poste.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelEmpl_poste.setText("Poste");

        labelEmpl_habilitation.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelEmpl_habilitation.setText("Habilitation");

        javax.swing.GroupLayout panelEmpl_formLayout = new javax.swing.GroupLayout(panelEmpl_form);
        panelEmpl_form.setLayout(panelEmpl_formLayout);
        panelEmpl_formLayout.setHorizontalGroup(
            panelEmpl_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpl_formLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEmpl_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEmpl_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmpl_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmpl_poste, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmpl_habilitation, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEmpl_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldEmpl_poste, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldEmpl_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldEmpl_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldEmpl_habilitation, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEmpl_formLayout.setVerticalGroup(
            panelEmpl_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpl_formLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(panelEmpl_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldEmpl_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmpl_nom))
                .addGap(27, 27, 27)
                .addGroup(panelEmpl_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmpl_prenom)
                    .addComponent(textFieldEmpl_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panelEmpl_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldEmpl_poste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmpl_poste))
                .addGap(31, 31, 31)
                .addGroup(panelEmpl_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldEmpl_habilitation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmpl_habilitation))
                .addContainerGap(245, Short.MAX_VALUE))
        );

        panelEmpl_valid.setBorder(javax.swing.BorderFactory.createTitledBorder("Valider"));

        buttonEmpl_insert.setLabel("Ajouter");

        buttonEmpl_delete.setLabel("Supprimer");

        buttonEmpl_update.setLabel("Modifier");

        javax.swing.GroupLayout panelEmpl_validLayout = new javax.swing.GroupLayout(panelEmpl_valid);
        panelEmpl_valid.setLayout(panelEmpl_validLayout);
        panelEmpl_validLayout.setHorizontalGroup(
            panelEmpl_validLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpl_validLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonEmpl_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonEmpl_update, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonEmpl_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelEmpl_validLayout.setVerticalGroup(
            panelEmpl_validLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpl_validLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEmpl_validLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonEmpl_insert, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(buttonEmpl_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonEmpl_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelEmplLayout = new javax.swing.GroupLayout(panelEmpl);
        panelEmpl.setLayout(panelEmplLayout);
        panelEmplLayout.setHorizontalGroup(
            panelEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 971, Short.MAX_VALUE)
            .addGroup(panelEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelEmplLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelEmpl_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(panelEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelEmpl_form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelEmpl_valid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        panelEmplLayout.setVerticalGroup(
            panelEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(panelEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelEmplLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelEmpl_list, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelEmplLayout.createSequentialGroup()
                            .addComponent(panelEmpl_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(panelEmpl_valid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addContainerGap()))
        );

        tabbedPanePers.addTab("Employés", panelEmpl);

        panelCand_list.setBorder(javax.swing.BorderFactory.createTitledBorder("Liste des candidats"));

        tableCand_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nom", "Prénom", "Date de naissance", "Pays"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPanelCand_list.setViewportView(tableCand_list);

        javax.swing.GroupLayout panelCand_listLayout = new javax.swing.GroupLayout(panelCand_list);
        panelCand_list.setLayout(panelCand_listLayout);
        panelCand_listLayout.setHorizontalGroup(
            panelCand_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCand_listLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelCand_list, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCand_listLayout.setVerticalGroup(
            panelCand_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCand_listLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelCand_list)
                .addContainerGap())
        );

        panelCand_form.setBorder(javax.swing.BorderFactory.createTitledBorder("Formulaire"));

        labelCand_nom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelCand_nom.setText("Nom");

        labelCand_prenom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelCand_prenom.setText("Prénom");

        labelCand_dateNaissance.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelCand_dateNaissance.setText("Date de naissance");

        labelCand_pays.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelCand_pays.setText("Pays");

        javax.swing.GroupLayout panelCand_formLayout = new javax.swing.GroupLayout(panelCand_form);
        panelCand_form.setLayout(panelCand_formLayout);
        panelCand_formLayout.setHorizontalGroup(
            panelCand_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCand_formLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCand_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCand_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCand_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCand_dateNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCand_pays, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCand_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldCand_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldCand_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldCand_pays, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCand_formLayout.setVerticalGroup(
            panelCand_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCand_formLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(panelCand_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldCand_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCand_nom))
                .addGap(27, 27, 27)
                .addGroup(panelCand_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCand_prenom)
                    .addComponent(textFieldCand_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(labelCand_dateNaissance)
                .addGap(34, 34, 34)
                .addGroup(panelCand_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldCand_pays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCand_pays))
                .addContainerGap(245, Short.MAX_VALUE))
        );

        panelCand_valid.setBorder(javax.swing.BorderFactory.createTitledBorder("Valider"));

        buttonCand_insert.setLabel("Ajouter");

        buttonCand_delete.setLabel("Supprimer");

        buttonCand_update.setLabel("Modifier");

        javax.swing.GroupLayout panelCand_validLayout = new javax.swing.GroupLayout(panelCand_valid);
        panelCand_valid.setLayout(panelCand_validLayout);
        panelCand_validLayout.setHorizontalGroup(
            panelCand_validLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCand_validLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonCand_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonCand_update, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonCand_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelCand_validLayout.setVerticalGroup(
            panelCand_validLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCand_validLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCand_validLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonCand_insert, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(buttonCand_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonCand_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelCandLayout = new javax.swing.GroupLayout(panelCand);
        panelCand.setLayout(panelCandLayout);
        panelCandLayout.setHorizontalGroup(
            panelCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 971, Short.MAX_VALUE)
            .addGroup(panelCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCandLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelCand_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(panelCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelCand_form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelCand_valid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        panelCandLayout.setVerticalGroup(
            panelCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(panelCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCandLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelCand_list, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelCandLayout.createSequentialGroup()
                            .addComponent(panelCand_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(panelCand_valid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addContainerGap()))
        );

        tabbedPanePers.addTab("Candidats", panelCand);

        javax.swing.GroupLayout panelPersLayout = new javax.swing.GroupLayout(panelPers);
        panelPers.setLayout(panelPersLayout);
        panelPersLayout.setHorizontalGroup(
            panelPersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPers_sort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabbedPanePers))
                .addContainerGap())
        );
        panelPersLayout.setVerticalGroup(
            panelPersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPers_sort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPanePers)
                .addContainerGap())
        );

        jTabbedPane.addTab("Personnes", panelPers);

        panelContrat.setBorder(javax.swing.BorderFactory.createTitledBorder("Contrats"));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Libellé"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jSplitPane2.setLeftComponent(jScrollPane2);

        javax.swing.GroupLayout panelContratLayout = new javax.swing.GroupLayout(panelContrat);
        panelContrat.setLayout(panelContratLayout);
        panelContratLayout.setHorizontalGroup(
            panelContratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContratLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane2)
                .addContainerGap())
        );
        panelContratLayout.setVerticalGroup(
            panelContratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContratLayout.createSequentialGroup()
                .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelMetier.setBorder(javax.swing.BorderFactory.createTitledBorder("Métiers"));
        panelMetier.setPreferredSize(new java.awt.Dimension(12, 231));

        javax.swing.GroupLayout panelMetierLayout = new javax.swing.GroupLayout(panelMetier);
        panelMetier.setLayout(panelMetierLayout);
        panelMetierLayout.setHorizontalGroup(
            panelMetierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 964, Short.MAX_VALUE)
        );
        panelMetierLayout.setVerticalGroup(
            panelMetierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );

        panelDomaine.setBorder(javax.swing.BorderFactory.createTitledBorder("Domaines de métiers"));
        panelDomaine.setPreferredSize(new java.awt.Dimension(12, 230));

        javax.swing.GroupLayout panelDomaineLayout = new javax.swing.GroupLayout(panelDomaine);
        panelDomaine.setLayout(panelDomaineLayout);
        panelDomaineLayout.setHorizontalGroup(
            panelDomaineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelDomaineLayout.setVerticalGroup(
            panelDomaineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelParamLayout = new javax.swing.GroupLayout(panelParam);
        panelParam.setLayout(panelParamLayout);
        panelParamLayout.setHorizontalGroup(
            panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelContrat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMetier, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
                    .addComponent(panelDomaine, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelParamLayout.setVerticalGroup(
            panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelContrat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelMetier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelDomaine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane.addTab("Contrats / Métiers", panelParam);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxPers_sortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxPers_sortActionPerformed
        // TODO add your handling code here:
        tabbedPanePers.setSelectedIndex(comboBoxPers_sort.getSelectedIndex());
    }//GEN-LAST:event_comboBoxPers_sortActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrameMegaCasting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrameMegaCasting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrameMegaCasting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrameMegaCasting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrameMegaCasting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCand_delete;
    private javax.swing.JButton buttonCand_insert;
    private javax.swing.JButton buttonCand_update;
    private javax.swing.JButton buttonEmpl_delete;
    private javax.swing.JButton buttonEmpl_insert;
    private javax.swing.JButton buttonEmpl_update;
    private javax.swing.JButton buttonOffre_delete;
    private javax.swing.JButton buttonOffre_insert;
    private javax.swing.JButton buttonOffre_update;
    private javax.swing.JButton buttonSociete_delete;
    private javax.swing.JButton buttonSociete_insert;
    private javax.swing.JButton buttonSociete_update;
    private javax.swing.JComboBox comboBoxPers_sort;
    private javax.swing.JComboBox comboBoxSociete_sort;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel labelCand_dateNaissance;
    private javax.swing.JLabel labelCand_nom;
    private javax.swing.JLabel labelCand_pays;
    private javax.swing.JLabel labelCand_prenom;
    private javax.swing.JLabel labelEmpl_habilitation;
    private javax.swing.JLabel labelEmpl_nom;
    private javax.swing.JLabel labelEmpl_poste;
    private javax.swing.JLabel labelEmpl_prenom;
    private javax.swing.JLabel labelOffre_1;
    private javax.swing.JLabel labelOffre_2;
    private javax.swing.JLabel labelOffre_3;
    private javax.swing.JLabel labelOffre_4;
    private javax.swing.JLabel labelSociete_Nom;
    private javax.swing.JLabel labelSociete_Responsable;
    private javax.swing.JLabel labelSociete_Siret;
    private javax.swing.JPanel panelCand;
    private javax.swing.JPanel panelCand_form;
    private javax.swing.JPanel panelCand_list;
    private javax.swing.JPanel panelCand_valid;
    private javax.swing.JPanel panelContrat;
    private javax.swing.JPanel panelDomaine;
    private javax.swing.JPanel panelEmpl;
    private javax.swing.JPanel panelEmpl_form;
    private javax.swing.JPanel panelEmpl_list;
    private javax.swing.JPanel panelEmpl_valid;
    private javax.swing.JPanel panelMetier;
    private javax.swing.JPanel panelOffre;
    private javax.swing.JPanel panelOffre_form;
    private javax.swing.JPanel panelOffre_list;
    private javax.swing.JPanel panelOffre_valid;
    private javax.swing.JPanel panelParam;
    private javax.swing.JPanel panelPers;
    private javax.swing.JPanel panelPers_sort;
    private javax.swing.JPanel panelSociete;
    private javax.swing.JPanel panelSociete_form;
    private javax.swing.JPanel panelSociete_list;
    private javax.swing.JPanel panelSociete_sort;
    private javax.swing.JPanel panelSociete_valid;
    private javax.swing.JScrollPane scrollPanelCand_list;
    private javax.swing.JScrollPane scrollPanelEmpl_list;
    private javax.swing.JScrollPane scrollPanelOffre_list;
    private javax.swing.JScrollPane scrollPanelSociete_list;
    private javax.swing.JTabbedPane tabbedPanePers;
    private javax.swing.JTable tableCand_list;
    private javax.swing.JTable tableEmpl_list;
    private javax.swing.JTable tableOffre_list;
    private javax.swing.JTable tableSociete_list;
    private javax.swing.JTextField textFieldCand_nom;
    private javax.swing.JTextField textFieldCand_pays;
    private javax.swing.JTextField textFieldCand_prenom;
    private javax.swing.JTextField textFieldEmpl_habilitation;
    private javax.swing.JTextField textFieldEmpl_nom;
    private javax.swing.JTextField textFieldEmpl_poste;
    private javax.swing.JTextField textFieldEmpl_prenom;
    private javax.swing.JTextField textFieldOffre_1;
    private javax.swing.JTextField textFieldOffre_2;
    private javax.swing.JTextField textFieldOffre_3;
    private javax.swing.JTextField textFieldOffre_4;
    private javax.swing.JTextField textFieldSociete_Nom;
    private javax.swing.JTextField textFieldSociete_Responsable;
    private javax.swing.JTextField textFieldSociete_Siret;
    // End of variables declaration//GEN-END:variables
}
