/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package megacasting;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;

import javax.swing.plaf.basic.BasicTabbedPaneUI;
import javax.swing.table.DefaultTableModel;

import megacasting.entity.Annonceur;
import megacasting.entity.Candidat;
import megacasting.entity.Diffuseur;
import megacasting.entity.Employe;
import megacasting.persistance.AnnonceurDAO;
import megacasting.persistance.CandidatDAO;
import megacasting.persistance.ConnectionBDD;
import megacasting.persistance.DiffuseurDAO;
import megacasting.persistance.EmployeDAO;

/**
 *
 * @author Mousse
 */
public class jPanelSociete extends javax.swing.JPanel {

	private List<Annonceur> annonceurs;
	private List<Diffuseur> diffuseurs;
    private Connection cnx;
	
    /**
     * Creates new form jPanelSociete
     */
    public jPanelSociete() {
        initComponents();
        
        //Connection a la base
        ConnectionBDD connectionBDD = ConnectionBDD.getInstance();
        cnx = connectionBDD.getConnection();
        //Refrech des listes 
        refreshAnnonceur();
        refreshDiffuseur();
        
        tabbedPaneSociete.setUI(new BasicTabbedPaneUI() {
            
            @Override
            protected int calculateTabAreaHeight(int tabPlacement, int horizRunCount, int maxTabHeight) {
                return 0; //To change body of generated methods, choose Tools | Templates.
            }
        });
    }

    
    /**
     * refrech list employe
     * @author Julien BUREAU <julien.bureau02@gmail.com>
     */
    public void refreshAnnonceur(){
    	
    	AnnonceurDAO annonceurDAO = new AnnonceurDAO();
    	annonceurs = new ArrayList<Annonceur>(annonceurDAO.list(cnx));
                
        DefaultTableModel model = (DefaultTableModel) tableAnnonceur_list.getModel();
        
        model.setNumRows(0);
        
        for (Annonceur a : annonceurs) {
            model.addRow(new Object[] {
                a.getNom(),
                a.getResponsable(),
                a.getSiret()
            });
        }
    }
    
    
    /**
     * refrech list diffuseur
     * @author Julien BUREAU <julien.bureau02@gmail.com>
     */
    public void refreshDiffuseur() {
    	
    	DiffuseurDAO diffuseurDAO = new DiffuseurDAO();
    	diffuseurs = new ArrayList<Diffuseur>(diffuseurDAO.list(cnx));
                
        DefaultTableModel model = (DefaultTableModel) tableDiffuseur_list.getModel();
        
        model.setNumRows(0);
        
        for (Diffuseur d : diffuseurs) {
            model.addRow(new Object[] {
                d.getNom(),
                d.getResponsable()
            });
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSociete_sort = new javax.swing.JPanel();
        comboBoxSociete_sort = new javax.swing.JComboBox();
        tabbedPaneSociete = new javax.swing.JTabbedPane();
        panelAnnonceur = new javax.swing.JPanel();
        panelAnnonceur_list = new javax.swing.JPanel();
        scrollPanelAnnonceur_list = new javax.swing.JScrollPane();
        tableAnnonceur_list = new javax.swing.JTable();
        panelAnnonceur_form = new javax.swing.JPanel();
        labelAnnonceur_nom = new javax.swing.JLabel();
        textFieldAnnonceur_nom = new javax.swing.JTextField();
        labelAnnonceur_responsable = new javax.swing.JLabel();
        textFieldAnnonceur_responsable = new javax.swing.JTextField();
        labelAnnonceur_siret = new javax.swing.JLabel();
        textFieldAnnonceur_siret = new javax.swing.JTextField();
        panelAnnonceur_valid = new javax.swing.JPanel();
        buttonAnnonceur_insert = new javax.swing.JButton();
        buttonAnnonceur_update = new javax.swing.JButton();
        buttonAnnonceur_delete = new javax.swing.JButton();
        panelDiffuseur = new javax.swing.JPanel();
        panelDiffuseur_list = new javax.swing.JPanel();
        scrollPanelDiffuseur_list = new javax.swing.JScrollPane();
        tableDiffuseur_list = new javax.swing.JTable();
        panelDiffuseur_form = new javax.swing.JPanel();
        labelDiffuseur_nom = new javax.swing.JLabel();
        textFieldDiffuseur_nom = new javax.swing.JTextField();
        labelDiffuseur_responsable = new javax.swing.JLabel();
        textFieldDiffuseur_responsable = new javax.swing.JTextField();
        panelDiffuseur_valid = new javax.swing.JPanel();
        buttonDiffuseur_insert = new javax.swing.JButton();
        buttonDiffuseur_update = new javax.swing.JButton();
        buttonDiffuseur_delete = new javax.swing.JButton();

        panelSociete_sort.setBorder(javax.swing.BorderFactory.createTitledBorder("Tri"));

        comboBoxSociete_sort.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2" }));
        comboBoxSociete_sort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxSociete_sortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSociete_sortLayout = new javax.swing.GroupLayout(panelSociete_sort);
        panelSociete_sort.setLayout(panelSociete_sortLayout);
        panelSociete_sortLayout.setHorizontalGroup(
            panelSociete_sortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSociete_sortLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(comboBoxSociete_sort, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSociete_sortLayout.setVerticalGroup(
            panelSociete_sortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSociete_sortLayout.createSequentialGroup()
                .addComponent(comboBoxSociete_sort, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelAnnonceur_list.setBorder(javax.swing.BorderFactory.createTitledBorder("Liste des annonceurs"));

        tableAnnonceur_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nom", "Responsable", "Siret"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPanelAnnonceur_list.setViewportView(tableAnnonceur_list);

        javax.swing.GroupLayout panelAnnonceur_listLayout = new javax.swing.GroupLayout(panelAnnonceur_list);
        panelAnnonceur_list.setLayout(panelAnnonceur_listLayout);
        panelAnnonceur_listLayout.setHorizontalGroup(
            panelAnnonceur_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnnonceur_listLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelAnnonceur_list, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelAnnonceur_listLayout.setVerticalGroup(
            panelAnnonceur_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnnonceur_listLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelAnnonceur_list)
                .addContainerGap())
        );

        panelAnnonceur_form.setBorder(javax.swing.BorderFactory.createTitledBorder("Formulaire"));

        labelAnnonceur_nom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelAnnonceur_nom.setText("Nom");

        labelAnnonceur_responsable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelAnnonceur_responsable.setText("Responsable");

        labelAnnonceur_siret.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelAnnonceur_siret.setText("N° Siret");

        javax.swing.GroupLayout panelAnnonceur_formLayout = new javax.swing.GroupLayout(panelAnnonceur_form);
        panelAnnonceur_form.setLayout(panelAnnonceur_formLayout);
        panelAnnonceur_formLayout.setHorizontalGroup(
            panelAnnonceur_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnnonceur_formLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAnnonceur_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAnnonceur_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAnnonceur_responsable, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAnnonceur_siret, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAnnonceur_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldAnnonceur_siret, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldAnnonceur_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldAnnonceur_responsable, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAnnonceur_formLayout.setVerticalGroup(
            panelAnnonceur_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnnonceur_formLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(panelAnnonceur_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldAnnonceur_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAnnonceur_nom))
                .addGap(27, 27, 27)
                .addGroup(panelAnnonceur_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAnnonceur_responsable)
                    .addComponent(textFieldAnnonceur_responsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panelAnnonceur_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldAnnonceur_siret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAnnonceur_siret))
                .addContainerGap(298, Short.MAX_VALUE))
        );

        panelAnnonceur_valid.setBorder(javax.swing.BorderFactory.createTitledBorder("Valider"));

        buttonAnnonceur_insert.setLabel("Ajouter");
        buttonAnnonceur_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAnnonceur_insertActionPerformed(evt);
            }
        });

        buttonAnnonceur_update.setLabel("Modifier");

        buttonAnnonceur_delete.setLabel("Supprimer");

        javax.swing.GroupLayout panelAnnonceur_validLayout = new javax.swing.GroupLayout(panelAnnonceur_valid);
        panelAnnonceur_valid.setLayout(panelAnnonceur_validLayout);
        panelAnnonceur_validLayout.setHorizontalGroup(
            panelAnnonceur_validLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnnonceur_validLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonAnnonceur_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonAnnonceur_update, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonAnnonceur_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelAnnonceur_validLayout.setVerticalGroup(
            panelAnnonceur_validLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnnonceur_validLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAnnonceur_validLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonAnnonceur_insert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonAnnonceur_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonAnnonceur_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelAnnonceurLayout = new javax.swing.GroupLayout(panelAnnonceur);
        panelAnnonceur.setLayout(panelAnnonceurLayout);
        panelAnnonceurLayout.setHorizontalGroup(
            panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 971, Short.MAX_VALUE)
            .addGroup(panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelAnnonceurLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelAnnonceur_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelAnnonceur_form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelAnnonceur_valid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        panelAnnonceurLayout.setVerticalGroup(
            panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 629, Short.MAX_VALUE)
            .addGroup(panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelAnnonceurLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelAnnonceur_list, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelAnnonceurLayout.createSequentialGroup()
                            .addComponent(panelAnnonceur_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(panelAnnonceur_valid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addContainerGap()))
        );

        tabbedPaneSociete.addTab("Annonceurs", panelAnnonceur);

        panelDiffuseur_list.setBorder(javax.swing.BorderFactory.createTitledBorder("Liste des diffuseurs"));

        tableDiffuseur_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nom", "Responsable"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPanelDiffuseur_list.setViewportView(tableDiffuseur_list);

        javax.swing.GroupLayout panelDiffuseur_listLayout = new javax.swing.GroupLayout(panelDiffuseur_list);
        panelDiffuseur_list.setLayout(panelDiffuseur_listLayout);
        panelDiffuseur_listLayout.setHorizontalGroup(
            panelDiffuseur_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDiffuseur_listLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelDiffuseur_list, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelDiffuseur_listLayout.setVerticalGroup(
            panelDiffuseur_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDiffuseur_listLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelDiffuseur_list)
                .addContainerGap())
        );

        panelDiffuseur_form.setBorder(javax.swing.BorderFactory.createTitledBorder("Formulaire"));

        labelDiffuseur_nom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelDiffuseur_nom.setText("Nom");

        labelDiffuseur_responsable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelDiffuseur_responsable.setText("Responsable");

        javax.swing.GroupLayout panelDiffuseur_formLayout = new javax.swing.GroupLayout(panelDiffuseur_form);
        panelDiffuseur_form.setLayout(panelDiffuseur_formLayout);
        panelDiffuseur_formLayout.setHorizontalGroup(
            panelDiffuseur_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDiffuseur_formLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDiffuseur_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDiffuseur_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDiffuseur_responsable, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDiffuseur_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldDiffuseur_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldDiffuseur_responsable, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDiffuseur_formLayout.setVerticalGroup(
            panelDiffuseur_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDiffuseur_formLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(panelDiffuseur_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldDiffuseur_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDiffuseur_nom))
                .addGap(27, 27, 27)
                .addGroup(panelDiffuseur_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDiffuseur_responsable)
                    .addComponent(textFieldDiffuseur_responsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(349, Short.MAX_VALUE))
        );

        panelDiffuseur_valid.setBorder(javax.swing.BorderFactory.createTitledBorder("Valider"));

        buttonDiffuseur_insert.setLabel("Ajouter");
        buttonDiffuseur_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDiffuseur_insertActionPerformed(evt);
            }
        });

        buttonDiffuseur_update.setLabel("Modifier");

        buttonDiffuseur_delete.setLabel("Supprimer");

        javax.swing.GroupLayout panelDiffuseur_validLayout = new javax.swing.GroupLayout(panelDiffuseur_valid);
        panelDiffuseur_valid.setLayout(panelDiffuseur_validLayout);
        panelDiffuseur_validLayout.setHorizontalGroup(
            panelDiffuseur_validLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDiffuseur_validLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonDiffuseur_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonDiffuseur_update, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonDiffuseur_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelDiffuseur_validLayout.setVerticalGroup(
            panelDiffuseur_validLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDiffuseur_validLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDiffuseur_validLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonDiffuseur_insert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonDiffuseur_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonDiffuseur_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelDiffuseurLayout = new javax.swing.GroupLayout(panelDiffuseur);
        panelDiffuseur.setLayout(panelDiffuseurLayout);
        panelDiffuseurLayout.setHorizontalGroup(
            panelDiffuseurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 971, Short.MAX_VALUE)
            .addGroup(panelDiffuseurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDiffuseurLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelDiffuseur_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(panelDiffuseurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelDiffuseur_form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelDiffuseur_valid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        panelDiffuseurLayout.setVerticalGroup(
            panelDiffuseurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 629, Short.MAX_VALUE)
            .addGroup(panelDiffuseurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDiffuseurLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelDiffuseurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelDiffuseur_list, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelDiffuseurLayout.createSequentialGroup()
                            .addComponent(panelDiffuseur_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(panelDiffuseur_valid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addContainerGap()))
        );

        tabbedPaneSociete.addTab("Diffuseurs", panelDiffuseur);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelSociete_sort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabbedPaneSociete))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSociete_sort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPaneSociete)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxSociete_sortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxSociete_sortActionPerformed
        // TODO add your handling code here:
        tabbedPaneSociete.setSelectedIndex(comboBoxSociete_sort.getSelectedIndex());
    }//GEN-LAST:event_comboBoxSociete_sortActionPerformed

    private void buttonAnnonceur_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAnnonceur_insertActionPerformed
        
        String nom = textFieldAnnonceur_nom.getText();
    	String responsable = textFieldAnnonceur_responsable.getText();
    	String siret = textFieldAnnonceur_siret.getText();
    	
    	try {
            Annonceur annonceur = new Annonceur(nom, responsable);
	    annonceur.setSiret(siret);
	    
	    AnnonceurDAO annonceurDAO = new AnnonceurDAO();
	    annonceurDAO.insert(cnx, annonceur);
	} catch (Exception e) {
	// TODO: handle exception
	}
    }//GEN-LAST:event_buttonAnnonceur_insertActionPerformed

    private void buttonDiffuseur_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDiffuseur_insertActionPerformed
        
        String nom = textFieldDiffuseur_nom.getText();
    	String responsable = textFieldDiffuseur_responsable.getText();
    	
    	try {
            Diffuseur diffuseur = new Diffuseur(nom, responsable);
	    
	    DiffuseurDAO diffuseurDAO = new DiffuseurDAO();
	    diffuseurDAO.insert(cnx, diffuseur);
	} catch (Exception e) {
	// TODO: handle exception
	}
    }//GEN-LAST:event_buttonDiffuseur_insertActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAnnonceur_delete;
    private javax.swing.JButton buttonAnnonceur_insert;
    private javax.swing.JButton buttonAnnonceur_update;
    private javax.swing.JButton buttonDiffuseur_delete;
    private javax.swing.JButton buttonDiffuseur_insert;
    private javax.swing.JButton buttonDiffuseur_update;
    private javax.swing.JComboBox comboBoxSociete_sort;
    private javax.swing.JLabel labelAnnonceur_nom;
    private javax.swing.JLabel labelAnnonceur_responsable;
    private javax.swing.JLabel labelAnnonceur_siret;
    private javax.swing.JLabel labelDiffuseur_nom;
    private javax.swing.JLabel labelDiffuseur_responsable;
    private javax.swing.JPanel panelAnnonceur;
    private javax.swing.JPanel panelAnnonceur_form;
    private javax.swing.JPanel panelAnnonceur_list;
    private javax.swing.JPanel panelAnnonceur_valid;
    private javax.swing.JPanel panelDiffuseur;
    private javax.swing.JPanel panelDiffuseur_form;
    private javax.swing.JPanel panelDiffuseur_list;
    private javax.swing.JPanel panelDiffuseur_valid;
    private javax.swing.JPanel panelSociete_sort;
    private javax.swing.JScrollPane scrollPanelAnnonceur_list;
    private javax.swing.JScrollPane scrollPanelDiffuseur_list;
    private javax.swing.JTabbedPane tabbedPaneSociete;
    private javax.swing.JTable tableAnnonceur_list;
    private javax.swing.JTable tableDiffuseur_list;
    private javax.swing.JTextField textFieldAnnonceur_nom;
    private javax.swing.JTextField textFieldAnnonceur_responsable;
    private javax.swing.JTextField textFieldAnnonceur_siret;
    private javax.swing.JTextField textFieldDiffuseur_nom;
    private javax.swing.JTextField textFieldDiffuseur_responsable;
    // End of variables declaration//GEN-END:variables
}
