/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package megacasting;

import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.swing.table.DefaultTableModel;

import megacasting.entity.Contrat;
import megacasting.entity.Domaine;
import megacasting.entity.Employe;
import megacasting.entity.Metier;
import megacasting.entity.Offre;
import megacasting.persistance.ConnectionBDD;
import megacasting.persistance.ContratDAO;
import megacasting.persistance.DomaineDAO;
import megacasting.persistance.EmployeDAO;
import megacasting.persistance.MetierDAO;
import megacasting.persistance.OffreDAO;

/**
 *
 * @author Mousse
 */
public class jPanelOffre extends javax.swing.JPanel {

	
	private List<Offre> offres;
        private List<Domaine> domaines;
        private List<Metier> metiers;
        private List<Contrat> contrats;
        
    private Connection cnx;
    
    
    /**
     * Creates new form jPanelOffre
     */
    public jPanelOffre() {
        initComponents();
        
        //Connection a la base
        ConnectionBDD connectionBDD = ConnectionBDD.getInstance();
        cnx = connectionBDD.getConnection();
        //Refrech des listes 
        refreshOffre();
        
        buttonOffre_insert.setEnabled(true);
        buttonOffre_update.setEnabled(false);
        buttonOffre_delete.setEnabled(false);
        
    }

    
    /**
     * refrech list offre
     * @author Julien BUREAU <julien.bureau02@gmail.com>
     */
    public void refreshOffre(){
    	
        //Initialisation de la table des offres
    	OffreDAO offreDAO = new OffreDAO();
    	offres = new ArrayList<Offre>(offreDAO.list(cnx));
                
        DefaultTableModel model = (DefaultTableModel) tableOffre_list.getModel();
        
        model.setNumRows(0);
        
        for (Offre o : offres) {
            model.addRow(new Object[] {
                o.getReference(),
                o.getLibelle(), 
                o.getDateDebPublication(),  
                o.getDomaine().getLibelle(),
                o.getMetier().getLibelle(),
                o.getContrat().getLibelle()
            });
 
        }
        
        //Initialisation de la combo box des domaines
        DomaineDAO domaineDAO = new DomaineDAO();
        domaines = new ArrayList<Domaine>(domaineDAO.list(cnx));
        
        for (Domaine d : domaines) {
            comboBoxOffre_domaine.addItem(d.getLibelle());
        }
        
        //Initialisation de la combo box des metiers
        metiers = refreshListMetiers();
        
        //Initialisation de la combo box des contrats
        ContratDAO contratDAO = new ContratDAO();
        contrats = new ArrayList<Contrat>(contratDAO.list(cnx));
        
        for (Contrat c : contrats) {
            comboBoxOffre_contrat.addItem(c.getLibelle());
        }
    }
    
    private List<Metier> refreshListMetiers() {
        
        comboBoxOffre_metier.removeAllItems();
        
        MetierDAO metierDAO = new MetierDAO();
        
        String domaineSelected = comboBoxOffre_domaine.getSelectedItem().toString();
        List<Metier> mesMetiers = new ArrayList<Metier>(metierDAO.listOfDomain(cnx, domaineSelected));
        
        for (Metier m : mesMetiers) {
            comboBoxOffre_metier.addItem(m.getLibelle());
        }
        
        return mesMetiers;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOffre_list = new javax.swing.JPanel();
        scrollPanelOffre_list = new javax.swing.JScrollPane();
        tableOffre_list = new javax.swing.JTable();
        panelOffre_form = new javax.swing.JPanel();
        labelOffre_reference = new javax.swing.JLabel();
        textFieldOffre_reference = new javax.swing.JTextField();
        labelOffre_libelle = new javax.swing.JLabel();
        textFieldOffre_libelle = new javax.swing.JTextField();
        labelOffre_datePublication = new javax.swing.JLabel();
        formattedTFOffre_datePublication = new javax.swing.JFormattedTextField();
        labelOffre_domaine = new javax.swing.JLabel();
        comboBoxOffre_domaine = new javax.swing.JComboBox();
        labelOffre_metier = new javax.swing.JLabel();
        comboBoxOffre_metier = new javax.swing.JComboBox();
        labelOffre_contrat = new javax.swing.JLabel();
        comboBoxOffre_contrat = new javax.swing.JComboBox();
        panelOffre_valid = new javax.swing.JPanel();
        buttonOffre_insert = new javax.swing.JButton();
        buttonOffre_update = new javax.swing.JButton();
        buttonOffre_delete = new javax.swing.JButton();

        panelOffre_list.setBorder(javax.swing.BorderFactory.createTitledBorder("Liste des offres"));

        tableOffre_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Référence", "Libellé", "Date de publication", "Domaine", "Métier", "Contrat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableOffre_list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableOffre_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableOffre_listMouseClicked(evt);
            }
        });
        scrollPanelOffre_list.setViewportView(tableOffre_list);

        javax.swing.GroupLayout panelOffre_listLayout = new javax.swing.GroupLayout(panelOffre_list);
        panelOffre_list.setLayout(panelOffre_listLayout);
        panelOffre_listLayout.setHorizontalGroup(
            panelOffre_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOffre_listLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelOffre_list, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelOffre_listLayout.setVerticalGroup(
            panelOffre_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOffre_listLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelOffre_list)
                .addContainerGap())
        );

        panelOffre_form.setBorder(javax.swing.BorderFactory.createTitledBorder("Formulaire"));

        labelOffre_reference.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelOffre_reference.setText("Référence");

        labelOffre_libelle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelOffre_libelle.setText("Libellé");

        labelOffre_datePublication.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelOffre_datePublication.setText("Date de publication");

        formattedTFOffre_datePublication.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        labelOffre_domaine.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelOffre_domaine.setText("Domaine");

        comboBoxOffre_domaine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxOffre_domaineActionPerformed(evt);
            }
        });

        labelOffre_metier.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelOffre_metier.setText("Métier");

        labelOffre_contrat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelOffre_contrat.setText("Contrat");

        javax.swing.GroupLayout panelOffre_formLayout = new javax.swing.GroupLayout(panelOffre_form);
        panelOffre_form.setLayout(panelOffre_formLayout);
        panelOffre_formLayout.setHorizontalGroup(
            panelOffre_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOffre_formLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOffre_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelOffre_formLayout.createSequentialGroup()
                        .addGroup(panelOffre_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelOffre_reference, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelOffre_libelle, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelOffre_datePublication, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelOffre_domaine, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelOffre_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldOffre_reference, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(textFieldOffre_libelle, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(comboBoxOffre_domaine, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(formattedTFOffre_datePublication)))
                    .addGroup(panelOffre_formLayout.createSequentialGroup()
                        .addComponent(labelOffre_metier, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboBoxOffre_metier, 0, 150, Short.MAX_VALUE))
                    .addGroup(panelOffre_formLayout.createSequentialGroup()
                        .addComponent(labelOffre_contrat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboBoxOffre_contrat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelOffre_formLayout.setVerticalGroup(
            panelOffre_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOffre_formLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(panelOffre_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldOffre_reference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelOffre_reference))
                .addGap(27, 27, 27)
                .addGroup(panelOffre_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOffre_libelle)
                    .addComponent(textFieldOffre_libelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panelOffre_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOffre_datePublication)
                    .addComponent(formattedTFOffre_datePublication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(panelOffre_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOffre_domaine)
                    .addComponent(comboBoxOffre_domaine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelOffre_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOffre_metier)
                    .addComponent(comboBoxOffre_metier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panelOffre_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOffre_contrat)
                    .addComponent(comboBoxOffre_contrat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(240, Short.MAX_VALUE))
        );

        panelOffre_valid.setBorder(javax.swing.BorderFactory.createTitledBorder("Valider"));

        buttonOffre_insert.setLabel("Ajouter");
        buttonOffre_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOffre_insertActionPerformed(evt);
            }
        });

        buttonOffre_update.setLabel("Modifier");

        buttonOffre_delete.setLabel("Supprimer");

        javax.swing.GroupLayout panelOffre_validLayout = new javax.swing.GroupLayout(panelOffre_valid);
        panelOffre_valid.setLayout(panelOffre_validLayout);
        panelOffre_validLayout.setHorizontalGroup(
            panelOffre_validLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOffre_validLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonOffre_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonOffre_update, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonOffre_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelOffre_validLayout.setVerticalGroup(
            panelOffre_validLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOffre_validLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOffre_validLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonOffre_insert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonOffre_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonOffre_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelOffre_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelOffre_form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelOffre_valid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelOffre_list, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelOffre_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelOffre_valid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @author Julien Bureau <julien.bureau02@gmail.com>
     * @param evt
     */
    private void buttonOffre_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOffre_insertActionPerformed

    	//test not null
    	if ((textFieldOffre_libelle.getText().equals("")) || (textFieldOffre_reference.getText().equals("")) || (formattedTFOffre_datePublication.getText().equals(""))) {
    		jFrameAlert jFrameAlertNull = new jFrameAlert("Vous ne pouvez laisser de champs vide.");
    		jFrameAlertNull.setVisible(true);
		}
    	else {
    		//test date convert
	    	SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
	    	String dateString = formattedTFOffre_datePublication.getText();
    		
	    	try {
	    		Date datePublication = formatter.parse(dateString);
	    	
	    		String libelle = textFieldOffre_libelle.getText();
	    		String reference = textFieldOffre_reference.getText();
	    		
	    		String libContrat = comboBoxOffre_contrat.getSelectedItem().toString();
	    		String libMetier = comboBoxOffre_metier.getSelectedItem().toString();
	    		String libDomaine = comboBoxOffre_domaine.getSelectedItem().toString();
	    		
	    		ContratDAO ctrlDAO = new ContratDAO();
	    		Contrat contrat = ctrlDAO.findFromLibelle(cnx, libContrat);
	    		
	    		MetierDAO metiDAO = new MetierDAO();
	    		Metier metier = metiDAO.findFromLibelle(cnx, libMetier);

	    		DomaineDAO domaDAO = new DomaineDAO();
	        	Domaine domaine = domaDAO.findFromLibelle(cnx, libDomaine);
        	
	        	Offre offre = new Offre(libelle, reference, datePublication, contrat, metier, domaine);
	        	
	        	jFrameOffreDetails detailsOffre = new jFrameOffreDetails(offre);
	            detailsOffre.setVisible(true);
	            
	    	} catch (Exception e) {
	    		jFrameAlert jFrameAlertNull = new jFrameAlert("Impossible de créer l'objet Offre. jPanelOffre.java ligne 400.");
	    		jFrameAlertNull.setVisible(true);
	    	}
		}//end else
	
    }//GEN-LAST:event_buttonOffre_insertActionPerformed

    private Long selectionOffre(java.awt.event.MouseEvent evt) {                           
        int row = tableOffre_list.rowAtPoint(evt.getPoint());
        Offre o = offres.get(row);
        
        textFieldOffre_libelle.setText(o.getLibelle());
        textFieldOffre_reference.setText(o.getReference());
        formattedTFOffre_datePublication.setValue(o.getDateDebContrat());
        
        // Not works
        comboBoxOffre_contrat.setSelectedItem(o.getContrat());
        comboBoxOffre_domaine.setSelectedItem(o.getDomaine());
        comboBoxOffre_metier.setSelectedItem(o.getMetier());
        
        buttonOffre_insert.setEnabled(false);
        buttonOffre_update.setEnabled(true);
        buttonOffre_delete.setEnabled(true);
        
        return o.getDomaine().getIdentifiant();
        
    }
    
    private void tableOffre_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableOffre_listMouseClicked
        // TODO add your handling code here:
        selectionOffre(evt);
    }//GEN-LAST:event_tableOffre_listMouseClicked

    private void comboBoxOffre_domaineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxOffre_domaineActionPerformed
        refreshListMetiers();// TODO add your handling code here:
    }//GEN-LAST:event_comboBoxOffre_domaineActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonOffre_delete;
    private javax.swing.JButton buttonOffre_insert;
    private javax.swing.JButton buttonOffre_update;
    private javax.swing.JComboBox comboBoxOffre_contrat;
    private javax.swing.JComboBox comboBoxOffre_domaine;
    private javax.swing.JComboBox comboBoxOffre_metier;
    private javax.swing.JFormattedTextField formattedTFOffre_datePublication;
    private javax.swing.JLabel labelOffre_contrat;
    private javax.swing.JLabel labelOffre_datePublication;
    private javax.swing.JLabel labelOffre_domaine;
    private javax.swing.JLabel labelOffre_libelle;
    private javax.swing.JLabel labelOffre_metier;
    private javax.swing.JLabel labelOffre_reference;
    private javax.swing.JPanel panelOffre_form;
    private javax.swing.JPanel panelOffre_list;
    private javax.swing.JPanel panelOffre_valid;
    private javax.swing.JScrollPane scrollPanelOffre_list;
    private javax.swing.JTable tableOffre_list;
    private javax.swing.JTextField textFieldOffre_libelle;
    private javax.swing.JTextField textFieldOffre_reference;
    // End of variables declaration//GEN-END:variables
}
